import type { Metadata } from "next";

import Navigation from "@/components/ui/Navigation";

import Providers from "../providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Providers>
        <Navigation />
        {children}
      </Providers>
    </>
  );
}
